### ISSUE TITLE
Avalon Work Type in Hyrax - Model

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#101]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1821
Originally created by @joncameron on *Thu, 13 Apr 2017 13:02:40 GMT*

---
### Description

Method from #1773 

This involves updating the models within in Hyrax and then dropping in spec tests as well. Generating a work type and defining descriptive metadata properties within hyrax. This is a first pass. The assumption is we will need to iterate. .

### Done looks like 

- [ ] Update the model
- [ ] Write spec tests
- [ ] tests should validate proper indexing. 

### Original Story
#1773

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1821#issuecomment-300190230
Originally created by @carrickr on *Tue, 09 May 2017 14:52:52 GMT*

---
This can probably be abandon.  We're going to run with generic work type until it breaks for us.  We've done enough investigation that we know how to make a work type in Hyrax if needed and we also know we don't want to do this unless we need to.  

Right now though all we need is #1854 to power our player though.

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1821#issuecomment-303868740
Originally created by @davidschober on *Wed, 24 May 2017 22:22:12 GMT*

---
@jlhardes I agree.

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1821#issuecomment-303843655
Originally created by @davidschober on *Wed, 24 May 2017 20:34:32 GMT*

---
@carrickr aren't the metadata folks using mods to describe our content? I'm a bit confused on how we can use a generic work type.

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1821#issuecomment-303859976
Originally created by @jlhardes on *Wed, 24 May 2017 21:41:58 GMT*

---
Maybe #1808 needs to happen before this issue is tackled or abandoned?

**Comment by yingfeng-iu** [comment]
References:
http://samvera.github.io/customize-metadata-model.html
https://github.com/nulib/donut/pull/114/files
https://github.com/avalonmediasystem/hyrax-demo
https://github.com/ruby-rdf/rdf-vocab
https://github.com/samvera/questioning_authority
