### ISSUE TITLE
Upstream PR For Versioned IIIF Manifest Requests

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#107]
### Description
Work on the controller for the content negotiation of presentation manifests (v2 vs v3).

### Done Looks Like
A pull request is made to Hyrax that incorporates the changes we've made for versioned requests.

child of https://github.com/samvera-labs/avalon-bundle/issues/228

**Comment by davidschober** [comment]
child of https://github.com/samvera-labs/avalon-bundle/issues/178

**Comment by davidschober** [comment]
@cjcolvar this is in core already I think. I'm going to close this. reopen it if I closet it mistakenly.

**Comment by mcwhitaker** [comment]
We may get back to this. @cjcolvar wants to wait a bit to see how things shake up.
