### ISSUE TITLE
Fix feature tests

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/avalon-bundle#117]
### Description
The feature tests hang or fail randomly.  Sometimes they pass when run individually. This is all feature tests from a browser's perspective.

This will be timeboxed to 5 and evaluated to see if further work needs to be done.

### Done Looks Like
Feature tests fixed and passing reliably.

**Comment by joncameron** [comment]
Valkyrie work will most likely rule this as unneeded; ticket not needed anymore for this.
