### ISSUE TITLE
Meet to discuss Matterhorn replacement

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#126]
## Description 

We need to discuss and document our plan for a matterhorn replacement. This ties into Avalon 7s general strategy. When we're done with this issue, we will have 1-2 options with benefits/ etc. noted. 

## Done looks like:

- discussion of whether we need a dashboard, etc. Can we bake it into Avalon 7
- Meeting takes place with key folks
- document is generated with plan
- work needed is issued out

## Related

Child of #86

**Comment by cjcolvar** [comment]
https://northwestern.box.com/s/4smygsjak4c09o7qrep4xn1jxpqutfxr

**Comment by cjcolvar** [comment]
Should look more into the work of NYT: https://open.blogs.nytimes.com/2016/11/01/using-microservices-to-encode-and-publish-videos-at-the-new-york-times/
Particularly https://github.com/NYTimes/video-transcoding-api which looks very similar to active_encode.
