### ISSUE TITLE
Update presenters with latest changes from Hyrax 2.1

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/avalon-bundle#128]
During the rc cycle of Hyrax 2.1, changes were made to the presenters when determining when to display a iiif viewer that checked if the user has access to the files.  Our presenter logic copied from Hyrax prior to these changes and need to be updated.  The PR where these changes were introduced was https://github.com/samvera/hyrax/pull/2846.  We should also check for other changes to the `universal_viewer?` method.

### Done Looks Like
- Update presenter logic
- Check for other changes to 'universal_viewer?' method and update code as needed

child of https://github.com/samvera-labs/avalon-bundle/issues/228

**Comment by cjcolvar** [comment]
This may be moot if we decide to move this code into a pull request to Hyrax core sooner rather than later.  Other things to watch out for when making that PR is `alias` vs. `alias_method`.

**Comment by davidschober** [comment]
@cjcolvar this is a stale ticket, correct? If so can you close?
