### ISSUE TITLE
Create a rubocop cop to ensure necessary files have license headers

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/avalon-bundle#134]
A rubocop cop would allow us to easily check that each new file gets a license header as part of the normal build process.  It also gives us a standard place to record which files should and shouldn't have license headers via rubocop's config file.

I did a prototype here: https://github.com/samvera-labs/avalon-bundle/commit/a8784600ca0ef34d4c6010acdd2198cde83bf8fb  This prototype would need to be altered to work properly and not be so brittle but proved the approach to be viable.  It might also be best to more this to the `license_header` gem.

### Description
Create a gem similar to Bixby because we have multiple repositories we need to run this over

- [ ] the cop should detect when the license is not present (and in the correct format)
- [ ] the cop should autocorrect the license when appropriate (rubocop -a), so that way in the future we just update the gem and the `bundle install && bundle exec rubocop` to update the license 

- Put this new gem in the gemfile

Related to #29.

**Comment by joncameron** [comment]
This can wait an be re-evaluated later. This is a before release type thing (formal release).
