### ISSUE TITLE
Rightsstatements.org Integration

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#156]
### Description
This is a part of our currrent grant. What does Hyrax do? Can we just work that into our model?

also notify Ryan for IMLS
child of #175

**Comment by jenyoung** [comment]
It's part of the basic metadata. https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb#L23

**Comment by davidschober** [comment]
So is this resolved as it's part of Hyrax basic metadata?

**Comment by jlhardes** [comment]
Yes, we should be able to work with however Hyrax includes rightsstatement.org URIs by default. Right now they are edm:rights, there's a [yml file](https://github.com/samvera/hyrax/blob/2.0-stable/lib/generators/hyrax/templates/config/authorities/rights_statements.yml) with the controlled list, and there are no suggestions from the metadata documentation/review to change that property.

**Comment by jlhardes** [comment]
I am trying to find the language in the current grant that describes what is expected for rights statements to verify that we're good with what Hyrax is doing by default. Can someone point to that part of the grant narrative?

**Comment by mcwhitaker** [comment]
@jlhardes This is the language:

In conjunction with the reuse enabled by IIIF A/V, this project will also include implementation of a Rights field for digital objects in Avalon with preconfigured options for Creative Commons licenses or RightsStatements.org statements. This field will pre-populate with linked open data URIs that will be added to the metadata for the digital objects. The entry form will allow for Rights fields to be assigned at varied levels of the time-based media with “more information” tooltip bubbles provided in the interface for basic guidance, as time-based media often has complicated rights issues at multiple levels. Work on implementation of a Rights field will be carried out in consultation with the Penn State University Libraries, which will provide in-kind support for creation of guidance materials by the Penn State Libraries Copyright Officer, Brandy Karl, who is an experienced Fair Use litigator, in conjunction with a Penn State instructional designer. The RightsStatements.org URIs will enable users to identify ghts for use of the objects, as well as allowing machine-readable statements consistent with data from DPLA and Europeana. Providing this feature in Avalon enables Avalon users to comply with the Rights recommendations of these aggregators.  

Later in the document there are details about what needs to be done for phases 2, 3, and 4.

**Comment by jenyoung** [comment]
Yes default Hyrax contains both the Creative Commons (needs to be updated to 4.0 licenses) and Rightsstatements.org URIs in yml files. As mentioned above, Hyrax currently does not allow for rights information at the File/FileSet level.

**Comment by jenyoung** [comment]
@rsteans this is the right story
