### ISSUE TITLE
Release version .3 of Avalon Work Type model wiki

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#166]
## Description

After validation of metadata model put a pin in it and release to developers. 

## Done looks like

- Metadata model is reviewed
- metadata model is released.

child of https://github.com/samvera-labs/avalon-bundle/issues/227

**Comment by jenyoung** [comment]
.2 has been on the wiki for a bit now. Or is this for a .3 version?

**Comment by davidschober** [comment]
yup, my bad.

**Comment by jlhardes** [comment]
Need to check the working document list of Avalon Audiovisual Work Model properties against a running version of current Avalon 7 development. Properties for 0.2 have been verified but others that required integration with Hyrax (license, spatial with geonames, etc) were not included in 0.2. Whatever is included now can update the work model and become the 0.3 version that is released.

**Comment by jlhardes** [comment]
Published model on Github wiki is 0.3 and reflects current status of Avalon Audiovisual Work Model: https://github.com/samvera-labs/avalon-bundle/wiki/Avalon-Audiovisual-Work-Model
