### ISSUE TITLE
Compare AV 6 form to AV 7

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#168]
## Description

As part of our work toward 7, we will review descriptive metadata in AV6 form and ensure that analogues exist, or identify differences for future development/discussion/ decisions.

## Done looks like

- Document differences between AV 6 and Avalon7
- Create tickets for future development/ discussion
- Verify everything on model is in form

child of https://github.com/samvera-labs/avalon-bundle/issues/227

**Comment by jlhardes** [comment]
Documenting differences between AV 6 and 7 forms in spreadsheet: https://docs.google.com/spreadsheets/d/1u3mXAqcDiJQD9dRyrc5-RVlaRLfKjPxBwqq__YEkjj8/edit?usp=sharing

**Comment by mcwhitaker** [comment]
@jenyoung  We did a board review today and wondered about this.  On slack I think you said that the stories related to the comparison have been  created. Is this story done, then?  Or do you still need to _verify everything on model is in form_ ?

**Comment by jenyoung** [comment]
@mcwhitaker yes, it is done.
