### ISSUE TITLE
Identify fields that need validation

### ISSUE THREAD

**Issue by jenyoung** [samvera-labs/avalon-bundle#171]
## Description

Identify fields that need validation and update the model spreadsheet. 

This is related to #131

## Done looks like:

- [ ] Fields identified that need validation
- [ ] model spreadsheet is updated and versioned

child of https://github.com/samvera-labs/avalon-bundle/issues/227

**Comment by jenyoung** [comment]
is this a dup to #202?

**Comment by joncameron** [comment]
Covered by #202
