### ISSUE TITLE
MEJS React IIIF Media player not rendered on first load of work

### ISSUE THREAD

**Issue by yingfeng-iu** [samvera-labs/avalon-bundle#180]
### Description
This is a follow up of https://github.com/samvera-labs/avalon-bundle/issues/145. When clicking on a Work item for the first time from search or from Avalon Home page, the MEJS React IIIF Media player doesn't render. Other than this case, the player will render for this work or any other work, for ex, after reload the same page, or go back to Home/Search page and click another work; it will also render if going to the URL for any work for the first time or afterwords.

### Done Looks Like
- The React MEJS component loads on the first load and any load afterwords.

**Comment by joncameron** [comment]
No longer relevant with all of the changes to avalon-bundle.
