### ISSUE TITLE
Documenation on IIIF player yarn importing

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#183]
_From @davidschober on July 6, 2018 15:1_

## Description

We have refactored our react application. We will need updated docs for other devs to use the application. 

## Done looks like

- docs written for #29
- docs reviewed by other devs

child of #https://github.com/samvera-labs/avalon-bundle/issues/178

_Copied from original issue: avalonmediasystem/avalon-iiif-player#30_

**Comment by adamjarling** [comment]
Documentation started here for Avalon Bundle:

https://github.com/samvera-labs/avalon-bundle/wiki/React-IIIF-Media-Player

**Comment by adamjarling** [comment]
Documentation for the `react-iiif-media-player`:

https://github.com/avalonmediasystem/react-iiif-media-player
