### ISSUE TITLE
Batch edit needs to be updated for audiovisual model

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/avalon-bundle#192]
Hyrax's default batch edit only show fields from BasicMetadata.  This form needs to be updated for the audiovisual model.

**Comment by mcwhitaker** [comment]
@cjcolvar  Would this be part of the work on the Batch Import/Export WG? Or do you think either way this would be an extension that we would have to work on?

**Comment by jenyoung** [comment]
@mcwhitaker this is for the batch edit function that exists in the Hyrax interface already.

**Comment by mcwhitaker** [comment]
Yeah, I get that, but my question is if the Batch WG will also look at this. I don't know the scope of the WG goals.  In the Permissioning WG we are hoping that the Batch WG will produce code that can be used by the UI as well, not just code that has to be submitted via background jobs.

**Comment by jlhardes** [comment]
I was thinking the Batch WG was only focusing on import/export but they do list batch update (which I think of as bulk edit) so maybe they will address it. https://wiki.duraspace.org/display/samvera/Hyrax+Batch+Import-Export+WG

**Comment by joncameron** [comment]
Roundtripping in Hyrax may solve this for us.
