### ISSUE TITLE
Investigation: How Hyrax Handles AdminSets/Collection Properties

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#204]
### Description
What will map to Avalon Units? What map to Avalon collections?

Find out what properties are used for AdminSets and other collections within Hyrax. What values are allowed (text, URIs)?

### Done Looks Like
Metadataists have a meeting and talk about it—new issues or other documents will come out of this. 

### Notes
In Donut, AdminSets are units, and collections exist that belong to the AdminSet.

child of avalonmediasystem/avalon#1763

**Comment by jlhardes** [comment]
Avalon Hyrax on test server defines following:

- Units
     - info:fedora/fedora-system:def/model#hasModel "AdminSet"
     - http://purl.org/dc/terms/title "[Name of AdminSet]"

- Collections
     - info:fedora/fedora-system:def/model#hasModel "Collection"
     - http://purl.org/dc/terms/title "[Name of Collection]"
     - http://schema.org/additionalType <gid://avalon/hyrax-collectiontype/3>

**Comment by jlhardes** [comment]
Need to add bf:heldBy with URI value for unit to AdminSet properties - works even if multiple AdminSets for one unit (Donut has University Archives and University Archives-Restricted as 2 AdminSets - both would have same bf:heldBy URI)

**Comment by jlhardes** [comment]
No need for Avalon-specific Unit model definition or Collection model definition (like Collection class in Avalon 6) - Hyrax includes distinguishing models from Fedora

**Comment by jlhardes** [comment]
How is a Collection tied to an AdminSet? It looks like a Work can be part of a Collection and a Work can be part of an AdminSet but Collections are not part of AdminSets. We think this can work but workflow has to include access to both AdminSet and Collection and assignment of AdminSet and Collection when uploading a new work.

**Comment by jlhardes** [comment]
See also avalonmediasystem/avalon#1286 and avalonmediasystem/avalon#1287
