### ISSUE TITLE
Run performance tests against Avalon 7

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#205]
## Description

We want to at least smoke test performance on Avalon bundle to start getting benchmarks and begin to figure out where or how we may need to optimize. 

## Done looks like

- review tests, verify that we have all the functionality 
- Figure out if there's a way to generate avalonish content 
- ID core tests (e.g. many membered collections, items with many sections, etc). 
- Run tests, publish if appropriate

**Comment by SumithBaddam** [comment]
Few issues encountered while doing performance testing,

1. Resource description is not working.Steps
Error: We're sorry, but something went wrong

**Comment by SumithBaddam** [comment]
Few issues encountered during performance testing,

1. When trying to edit "Resource description" for 100 section item it's throwing ERROR: "We're sorry, but something went wrong."

2. When trying to edit the captions in "Structures" section of 100 section item, it is throwing ERROR: "There was a problem storing the file".

3. When trying to edit the "ManageFiles" section of 100 section item, it is throwing ERROR: "We're sorry, but something went wrong."

**Comment by cjcolvar** [comment]
@SumithBaddam There was a problem with the upgrade of mallorn that missed a step and was breaking ingest.  Could you please retest those three issues you found?

**Comment by SumithBaddam** [comment]
@cjcolvar I retested the issues. 1st step seems to work now. But the others (1 and 3) are still throwing same error. 

Meanwhile I noticed another error with selected items tab. It is displaying the number of items selected wrong. It seems to add 1 for the total items selected. Example, when I select 3 items it shows as 4 and when I remove all it still shows 1 item selected.

**Comment by phuongdh** [comment]
I'm seeing this when trying to update label of a section

![image.png](https://images.zenhubusercontent.com/5cc1c79d0ce5f07dcc92eebd/7d22ca61-7967-41b5-9e13-4c24c740f7d4)

**Comment by phuongdh** [comment]
Deleting section still fails with "Stack level too deep"

**Comment by SumithBaddam** [comment]
Performance testing is completed for most of the tests except for deleting the 100 section item. It's throwing "SystemStackError: stack level too deep" error.

The metrics can be accessed in the below box location.
https://northwestern.box.com/s/qx994ez53wgfiucxb8bvz016coo82kap

**Comment by mcwhitaker** [comment]
@joncameron Performance for _Adding 100 items to playlist_  is now taking almost twice as long as our benchmark numbers. It seems to merit investigation. Sumith said he ran it multiple times in mallorn to get the current value of 19s and before it took 10s.

**Comment by joncameron** [comment]
Created #3884 in response to the degraded performance for adding items to playlists.
