### ISSUE TITLE
Discuss View Transcoding Status on Item Page

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#208]
### Description
As a user in a staff role, if files on the item are currently transcoding, I want to view the current progress.

### Questions
- What should be shown to the user?
- What level of detail of progress will be available (and what is ideal?), and what will be shown?
- Should a progress bar be shown at all, or are there other options to be considered? For example, green checks as subtasks within the job move along
  - This could be something even simpler than a progress bar to start

This will most likely be per-masterfile, and not represent progress or details on derivatives generated.

ActiveEncode doesn't know what outputs it will be producing, which is an important consideration. Baked into ActiveEncode right now is a progress bar and a textual representation of the current step.

With some adapters it will be more guesswork regarding the percentage of progress. ElasticTranscode may be more guesswork, FFmpeg may be closer to real time. "In Progress" and "Done" could work for ElasticTranscode.

This could be a React component that hits the ActiveEncode endpoint that displays progress bar and current step.

### Done Looks Like
- A meeting is held and transcoding dashboard look and requirements are hammered out
- Wireframes and mockups developed
- Further stories written

### Meeting Deliverables
https://ninjamock.com/s/MBVKMRx

![screen shot 2019-03-07 at 9 11 36 am](https://user-images.githubusercontent.com/1406618/53962491-342cf600-40b9-11e9-9aa6-783038b63974.png)

child of https://github.com/samvera-labs/avalon-bundle/issues/250

**Comment by joncameron** [comment]
Prereq stories - 
1) how do items maintain a relationship with their ActiveEncode processes?
2) should ActiveEndcode have an endpoint by which process can be queried
Ultimately, this story becomes "hit the endpoint, display the returned value in a progess bar"

**Comment by joncameron** [comment]
Future thing to look at: ActionCable, and pushing instead of pulling.

**Comment by joncameron** [comment]
(removed from Sprint 171- needs refinement)

**Comment by mcwhitaker** [comment]
@joncameron @davidschober  - If I remember correctly, this discussion is just between the two of you. Correct? I can work on scheduling a meeting if we need others.

**Comment by davidschober** [comment]
I believe it’s just us.

**Comment by joncameron** [comment]
This can just be me and David. I may ask Chris for some ActiveEncode process details, but I don't think he needs to be there.

**Comment by joncameron** [comment]
https://ninjamock.com/s/MBVKMRx
