### ISSUE TITLE
Transcoding Dashboard

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#210]
### Description
As a user in a staff role or administrator, I want to view a dashboard of active transcoding jobs.
So that site administrators/managers have access to a **basic** tabular monitoring dashboard.

* filtering by collection
* drill down capabilities
* analytics/stats

**Comment by mcwhitaker** [comment]
I think that we need to better understand what a "basic tabular monitoring dashboard" is. For instance, drilling down is usually considered an advanced feature and it is being asked for. We don't all think as "basic" the same way.

1. filtering by collection - this is well defined
2. drill down - need clarification on what type of data will be used for drilling down
3. analytics/stats - need clarification on what sort of stats will be gathered.

Maybe a mockup of the dashboard with envisioned available actions marked will help get us all on the same page.

**Comment by joncameron** [comment]
Closing in favor of breaking off stories from a new epic for 0.5.
