### ISSUE TITLE
Transcode via ElasticTranscode

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#211]
## Description

Update ElasticTranscode adapter for transcoding via ActiveEncode. 

## Notes
Derivatives should be placed in a proper bucket.

## Done Looks Like
- Configure and ensure that the ElasticTranscode adapter works with avalon-bundle
- Test avalon-bundle in an ElasticTranscode configuration and create issues as needed
child of #229

**Comment by davidschober** [comment]
This is a test issue.

**Comment by phuongdh** [comment]
ElasticTranscoder adapter didn't work so I changed this ticket into making the adapter functional. Will split the avalon-bundle work to a new ticket.
