### ISSUE TITLE
Upstream PR for IIIF viewer flexibility

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/avalon-bundle#213]
Currently Hyrax assumes usage of UV for IIIF viewing with methods like `#universal_viewer?` and lacks the ability to choose a different viewer.  avalon-bundle has the ability for a Presenter class to choose it's IIIF preferred viewer.  This would be a good change to push upstream to avoid needing to overwrite views within the Avalon IIIF viewer Hyrax plugin.

Existing code:
Override of show view to make iiif viewer generic instead of UV only: https://github.com/samvera-labs/avalon-bundle/blob/master/app/views/hyrax/base/show.html.erb#L42 https://github.com/samvera-labs/avalon-bundle/blob/master/app/views/hyrax/base/_representative_media.html.erb#L20-L22 https://github.com/samvera-labs/avalon-bundle/tree/master/app/views/hyrax/base/iiif_viewers

**Comment by mcwhitaker** [comment]
Abandoned and is included in the work of #214.
