### ISSUE TITLE
Create Hyrax plugin for Avalon IIIF viewer

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/avalon-bundle#214]
Making a plugin version of the code in avalon-bundle that enables and renders the Avalon IIIF player with support for either Hyrax default derivatives or ActiveEncode-style multiple external derivatives.  This includes detailed instructions in the README for installing and using the plugin.

**Comment by mcwhitaker** [comment]
@carrickr please write the ticket for the work that is left here so we can close this one tomorrow.
