### ISSUE TITLE
Create training video on using form editor in 6

### ISSUE THREAD

**Issue by jenyoung** [samvera-labs/avalon-bundle#222]
### Description 

Create training video on using form editor in 6

Also update any related documentation

**Comment by joncameron** [comment]
@jenyoung Is this and #223 and #224 referring to training for Avalon 6?

**Comment by jenyoung** [comment]
@joncameron yes i put it on the wrong board.

**Comment by joncameron** [comment]
Moved to avalonmediasystem/avalon#3107
