### ISSUE TITLE
I want to be able to actually stream video

### ISSUE THREAD

**Issue by mcwhitaker** [samvera-labs/avalon-bundle#234]
### Description

We need to use the streaming server to stream from our avalon-bundle.

### Done looks like

Derivatives need to be distributed to the streaming locations. No preference as to the streaming server. Real streaming on fluorine.

hyrax-active_encode:
- [x] Fix PersistDeriativeService to persist location URL
- [ ] Add external flag to derivative model, solr, etc (do later)

hyrax-iiif_av:
- [x] Add mapping lambda config + call in presenter module

avalon-bundle:
- [x] Avalon uses hyrax_active-encode
- [x] Avalon gets/calculates m3u8 URL from active-encode
- [x] Avalon embeds m3u8 on view page
- [x] Put nginx back in docker-compose

react-iiif-media-player:
- [x] Make player work with m3u8 files

**Comment by phuongdh** [comment]
Needs tasking

**Comment by mcwhitaker** [comment]
Tasks in "done looks like" sufficient for now.
