### ISSUE TITLE
Docker dev enhancements

### ISSUE THREAD

**Issue by phuongdh** [samvera-labs/avalon-bundle#237]
- [x] Use sqlite so schema.rb doesn't get updated too often
- [x] Bring in Connect workshop improvements (webpacker, Mac fix)
- [x] Dev Dockerfile should live in avalon-bundle repo
- [x] Update image build in Bamboo to use new repo

**Comment by cjcolvar** [comment]
Do we need to make any changes to the containers being built?  I remember we had to rebuild the avalon container for the workshop.

**Comment by phuongdh** [comment]
Did not see webpacker fix in connect18 workshop.

**Comment by phuongdh** [comment]
Decided to run `webpack-dev-server` only when we need it
