### ISSUE TITLE
Upstream PR for IIIF Viewer Choice

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#240]
Description
IIIF viewer choice was added as a feature in the `hyrax-iiif_av` plugin which includes an override of a Hyrax view and renaming of a method.  These changes are potential non-backwards compatible changes so would be good to get into the Hyrax 3.0.0 release.

See:
https://github.com/samvera-labs/hyrax-iiif_av/blob/master/app/views/hyrax/base/_representative_media.html.erb
https://github.com/samvera-labs/hyrax-iiif_av/blob/master/app/presenters/concerns/hyrax/iiif_av/displays_iiif_av.rb#L30-L40
https://github.com/samvera/hyrax/blob/master/app/views/hyrax/base/show.html.erb#L24
and line 18 above

Done Looks Like
A pull request is made to Hyrax that incorporates the changes we've made for iiif viewer choice.

child of #228.
child of #178.

**Comment by cjcolvar** [comment]
Description
IIIF viewer choice was added as a feature in the `hyrax-iiif_av` plugin which includes an override of a Hyrax view and renaming of a method.  These changes are potential non-backwards compatible changes so would be good to get into the Hyrax 3.0.0 release.

See:
https://github.com/samvera-labs/hyrax-iiif_av/blob/master/app/views/hyrax/base/_representative_media.html.erb
https://github.com/samvera-labs/hyrax-iiif_av/blob/master/app/presenters/concerns/hyrax/iiif_av/displays_iiif_av.rb#L30-L40
https://github.com/samvera/hyrax/blob/master/app/views/hyrax/base/show.html.erb#L24
and line 18 above

Done Looks Like
A pull request is made to Hyrax that incorporates the changes we've made for iiif viewer choice.

child of #228.
child of #178.

**Comment by cjcolvar** [comment]
Upstream PR merged and PR created in `hyrax-iiif_av` for when it gets into a hyrax release.
