### ISSUE TITLE
Investigation - IIIF Manifests Contain Poster Image

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#262]
### Notes
What are the semantics of poster canvas vs. thumbnail? 
- Decide which one of these we want to do, then implement.
The implementation for thumbnail poster that Chris had done before had them being the same image-2 files, but the same content. Do we change those.

Poster canvas is new in v3--thumbnail existing before. The space where the canvas will go before it's there--the interaction could be different. Poster canvas if you had a IIIF image server holding the poster image, your interaction could be zooming on the poster--you could, since it's a canvas. Thumbnail is meant to be more static, although it could probably also be backed by an image server. Clients will most likely use poster canvas to display something before the main canvas kicks in.

To do: Look over the spec again and see if the British Library has forged a path.

**Comment by cjcolvar** [comment]
@bkeese and I looked over the spec again and decided that we should implement both thumbnail and posterCanvas.  Thumbnail would be for quick navigational help and poster for prior to playing the main content of a canvas.  (See https://iiif.io/api/presentation/3.0/#postercanvas for more details.)

Our plan of work would be to add thumbnail and posterCanvas support in `iiif_manifest`, implement it in `avalon-bundle`, then update the react player to make use of these two new properties.

For implementing in `iiif_manifest`, posterCanvas would be a hash of five keys (url, height, width, format, type) that would get passed to `DisplayContent` and would be run through the `CanvasBuilder`.  Thumbnail would just be a url.

Within `hyrax-iiif_av`, we could continue using the same image for both of these (the stock hyrax thumbnail derivative) for now if the image quality is high enough for using as a poster.  (Eventually we'll want to have different poster and thumbnail images coming from active_encode but we already have the stock hyrax thumbnails so we can use them for first implementation.)

**Comment by joncameron** [comment]
New issues:
- https://github.com/avalonmediasystem/avalon-iiif-player/issues/32
- https://github.com/samvera-labs/avalon-bundle/issues/275
- https://github.com/samvera-labs/avalon-bundle/issues/276
