### ISSUE TITLE
Docker OSX Dev Environment Fix

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#27]
### Description
Docker's giving a lot of trouble on a number of fronts.

For OSX environment, webpack 'pack' files are not compiling.  Need to figure out a solution otherwise all JavaScript work is blocked.

### Done Looks Like
- Docker issues are ironed out.
- `.js`, `.css`, `.scss` files in `app/javascript/packs` folder compile.

**Comment by adamjarling** [comment]
Current approach is to bypass Docker.
