### ISSUE TITLE
Port IIIF Auth work from Avalon 6 to hyrax-iiif_av

### ISSUE THREAD

**Issue by mcwhitaker** [samvera-labs/avalon-bundle#274]

**Comment by cjcolvar** [comment]
Final work in https://github.com/samvera-labs/hyrax-iiif_av/pull/22

**Comment by cjcolvar** [comment]
Finally tested this on fluorine with UV and found two issues:
1) Window opened with AuthService Id (sign in url) doesn't autoclose
2) AuthTokenService isn't sending JS message properly so UV never receives it

**Comment by davidschober** [comment]
@cjcolvar I see a PR attached to this. Is this in play/ done?

**Comment by bkeese** [comment]
@davidschober This work has been started, but its completion has been postponed until later.

**Comment by cjcolvar** [comment]
Cypress test is failing on the login window not autoclosing, but it doesn't catch the sameOrigin issue.
https://gist.github.com/cjcolvar/7d21dc29a148e8098d152e69e243bca5
