### ISSUE TITLE
Rails 5.2 Support

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#279]
### Description
Rails versions below 5.2 will soon be deprecated with the upcoming release of Rails 6 and will only receive severe security updates.

### Done Looks Like
Avalon 7 runs on Rails 5.2.

**Comment by joncameron** [comment]
This will wait until Hyrax is on 5.2. Hyrax can start to be tested on Rails 5.2 soon.

**Comment by davidschober** [comment]
@cjcolvar is there something the Avalon team needs to take action on here? Or is this just a sanity check when Hyrax upgrades?

**Comment by cjcolvar** [comment]
Once Hyrax upgrades, we'll need to upgrade as well (including the hyrax plugins we've written) which will involve some work.

**Comment by joncameron** [comment]
Done with our Hyrax 3 work.
