### ISSUE TITLE
Display Link to Transcode Dashboard in Hyrax Dashboard Sidebar Nav

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#282]
### Description
Adding a link to the transcoding jobs index view to the Hyrax dashboard.

### Done Looks Like
- "Transcoding Jobs" link displays in the Hyrax sidebar nav.

### Mockup
![screen shot 2019-03-07 at 9 25 41 am](https://user-images.githubusercontent.com/1406618/53968167-8b849380-40c4-11e9-9cfb-29255c8bd759.png)

### Notes
Low estimate for this issue since implementation will be simple after the upstream strategy (#283) is defined.
child of #299
blocked by #283

**Comment by joncameron** [comment]
Investigate: upstream Hyrax work to inject new menu items into the sidebar. This would let us not have to override the view and makes sense long term for Hyrax.

**Comment by bkeese** [comment]
<i class="fas fa-tasks-alt"></i>
