### ISSUE TITLE
Investigation: Hyrax Dashboard Sidebar Nav Menu Items

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#283]
### Description
Talking with Hyrax devs to investigate the possibility of creating new menu items without overriding the view for the dashboard.

### Done Looks Like
- Investigate how this could happen in Hyrax
- Implement if reasonable

child of #299

**Comment by joncameron** [comment]
@yingfeng-iu If you remember any of how this worked when you were looking into it previously, can you add any comment or information? Thanks!

**Comment by joncameron** [comment]
@yingfeng-iu If you remember any of how this worked when you were looking into it previously, can you add any comment or information? Thanks!

**Comment by cjcolvar** [comment]
PR created here: https://github.com/samvera/hyrax/pull/3878

**Comment by cjcolvar** [comment]
This was merged to hyrax master (pre-release 3.0.0).  We'll need to upgrade to hyrax 3.0 to make use of this (and remove our monkey-patches).
