### ISSUE TITLE
Avalon/Hyrax Permissions Document

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#290]
### Description
Document written to explicate permissions needs for Avalon 7. Look at permissions in Avalon , go over ideas of implementation in Hyrax, and reflect on what was talked about with Hyrax PO/devs.

### Done Looks Like
- Permissions white paper written for evaluation by team members, including stakeholders.
- https://docs.google.com/document/d/1nsU5Vs7PPrq3X4KPIvNY-zN_dmjERe0hTGba8TzsO8M/edit#

child of https://github.com/samvera-labs/avalon-bundle/issues/301

**Comment by cjcolvar** [comment]
Hyku is using rolify, rather than hydra-role-management.
