### ISSUE TITLE
Write Instructions for AWS Installs

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#298]
### Description
Documentation should be written for the installation methods developed for AWS. 

### Done Looks Like
- Documentation written for Terraform/AMI and made available on Confluence/Github Wiki.

child of https://github.com/avalonmediasystem/avalon/issues/3230

**Comment by phuongdh** [comment]
https://github.com/phuongdh/avalon-terraform/blob/master/README.md

**Comment by davidschober** [comment]
Phuong, This looks good. Can this be moved to the avalonmediasystem org?

**Comment by phuongdh** [comment]
I plan to do that as soon as the repo stabilizes.
