### ISSUE TITLE
Scope needs for Permissions (outside vendor)

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#300]
We may have some funding for finishing our core permissions work. We will need to write a concise (one - two page) document scoping the needs. Per our white paper, we should favor Hyrax native solutions as much as possible. 

## Done looks like
- Meeting is held with core team to design permission needs (should we rope in Tom Johnson?)
- Write white paper
- Get any sign off from Sn. Leaders
- Deliver to Vendors

child of #301

**Comment by mcwhitaker** [comment]
@davidschober I think we should bring in Tom, but only after we have worked on a list of items.

**Comment by davidschober** [comment]
Agreed! Sounds like a plan.

**Comment by cjcolvar** [comment]
Next step: do a dive and bring things up for later review.
