### ISSUE TITLE
ActiveEncode Tour and Derivative Generation Discussion

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#31]
### Description
Discussing flow of derivative generation at a high level, to understand our use cases, and plan how this will be implemented and the phases to do so. This is assuming Hyrax 2.1. 

Chris has offered to give a tour of ActiveEncode, so that will take a large part of the initial discussion. This is with an eye toward giving POs and other team members some familiarity with the currently methods Hyrax uses to generate derivatives and the architecture behind the scenes.

### Done looks like

- Meeting scheduled
- Further issues or documents generated as needed

child of https://github.com/samvera-labs/avalon-bundle/issues/176

**Comment by davidschober** [comment]
https://github.com/samvera-labs/avalon-bundle/issues/176
