### ISSUE TITLE
IP Address Investigation

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#319]

**Comment by cjcolvar** [comment]
hydra-access-controls has a basic implementation of IP-based permissions which I don't know any applications that make use of.  I did not have time to try it out but it looks like the approach taken is to map IP/IP ranges to groups then add these groups to a user's ability just like external groups would.  This seems to be a simpler approach than the APO approach taken in Avalon 6.  The default implementation in hydra-access-controls uses a yml file to load these group mappings.  This is in addition to role_map.yml.  We could make use of this approach but we'd like a UI for managing these groups just like we want a UI alternative to role_map.yml for ad hoc groups like we have in Avalon 6.  I'd expect that we'd add the ability to add IP/IP ranges alongside users in the ad hoc group management interface.  We would not add the ability to add IPs or IP ranges to the sharing or individual works but always have the IP/IP ranges behind a group.  This is probably better to have this abstraction layer to avoid having to update lots of objects when IP ranges get remapped.  Therefore the bulk of the work on this feature would be on the UI side of the ad hoc group management interface.  Some work would need to be done to use the IP-based ability in Hyrax (or avalon-bundle) and test out this approach more but this should be fairly small.

Links to relevant code:
https://github.com/samvera/hydra-head/blob/master/hydra-access-controls/lib/hydra/ip_based_groups.rb
https://github.com/samvera/hydra-head/blob/master/hydra-access-controls/app/models/concerns/hydra/ip_based_ability.rb
https://github.com/samvera/hydra-head/blob/master/hydra-core/app/controllers/concerns/hydra/controller/ip_based_ability.rb

**Comment by mcwhitaker** [comment]
@cjcolvar  - Thanks for this one, also. If I am reading this correctly, you are saying that the work to use the IP-based abilities should be fairly small. Would the UI work to manage the ad hoc groups also be fairly small? Given our recent experience with UI work, I don't have a sense of what small means for UI. Weeks? Days? Hours?

**Comment by cjcolvar** [comment]
I think the UI work would be a medium-ish job 8 to 13 depending on the design.  If we were to use something like hydra-role-management then it might be on the higher side just because we'd have to learn it's assumptions and probably have to work around some of them.  My estimate here is for implementing the whole ad-hoc/system group management UI including the ability to add IP/IP ranges to groups.
