### ISSUE TITLE
Technical Approach to UI - Investigation/Planning

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#326]
### Descriptive summary
How will we implement styling and UI elements in Avalon 7 is an open question. What are some of the expectations for how this work will go? What are possible challenges? How have existing Hyrax apps done this? Preliminary answers to these will help us plan for upcoming cycles.

### Done Looks Like
- Front-end developers meet to discuss ideas
- Possible approaches are outlined
- Recommendations made
- Document or presentation assembled (doesn't have to be extensive!) to present possible plans to POs and stakeholders

**Comment by adamjarling** [comment]
After a discussion today (6/25/2019), we will move forward with crafting some documentation here on approaches.  Basic content will be something like:
- One approach - Rails views / vanilla JS/jQuery
- Second approach - React components
- Third approach - find existing repository components or packages we can easily pull into the avalon-bundle.

We can make a case for / against each, whether it's a possibility, what it would look like in terms of development approach, and what the risks are with each?

**Comment by adamjarling** [comment]
For Google doc access:  adam.arling@u.northwestern.edu

**Comment by mcwhitaker** [comment]
@adamjarling yes, we will need the proposal and pros and cons. Having this ready for f2f is good.

Did you mean to offer us a link to a google doc? Your email address is showing instead.

**Comment by adamjarling** [comment]
@mcwhitaker Got it.  Sorry, my email address above was for Dananji in case she created the doc before I did.  We'll deliver a Google doc link and/or paste the contents in this issue to store wherever Avalon sees fit.  Have fun in Germany!

**Comment by adamjarling** [comment]
https://docs.google.com/document/d/1z5pggNcam-sTp4OVrbJP8tiTaHZDdrtUL0qEwpW7Ntg/edit?usp=sharing
