### ISSUE TITLE
Add Player API to Standalone Player

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#344]
### Description
For parity with Avalon 6, Avalon 7 needs to implement the same Player API. 

### Current API Documentation
https://wiki.dlib.indiana.edu/display/VarVideo/Player+API

### Done Looks Like
- Implement Player API in standalone player
- Front-end devs provide thoughts on API calls—anything to change or rename?

**Comment by cjcolvar** [comment]
Wait until we have embedded view to begin this.
