### ISSUE TITLE
Add Docker example commands to README

### ISSUE THREAD

**Issue by phuongdh** [samvera-labs/avalon-bundle#345]
### Description
Information helpful for using our Docker install should be added to the README.

### Done Looks Like
Add troubleshooting commands:
- [ ] How to start fresh again (down -v, pull, ps, restart)
- [ ] What commands to try when things are broken (logs/tail)
- [ ] exec bash, attach to byebug
Assuming unfamiliarity with Docker.

**Comment by joncameron** [comment]
This information is already present in the readme for the repo.
