### ISSUE TITLE
Documenting Scenarios for Avalon

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#349]
### Descriptive summary

Expand on the 3 scenarios regarding future directions for Avalon discussed at the face to face meeting and write them into a document for stakeholders to review.

### Done Looks Like

- 1-2 page document written describing and explaining the scenarios, and how they will impact Avalon.

**Comment by davidschober** [comment]
completed https://northwestern.box.com/s/yytgui8lnx3vbvtheslee4xm3ojfolxu 

Will review with stakeholders.

**Comment by mcwhitaker** [comment]
@davidschober @joncameron  - Is there a 4th scenario?  I am thinking that for scenario 3, to minimize the "risk" of not having enough staff while the proposal shapes up, we could use scenario 1 as a temporary solution. By this I mean - release Avalon 7 as an upgrade to Avalon 6 (not a rewrite) while the support and partnership for a Hyrax-based solution shapes up.

**Comment by davidschober** [comment]
I agree. I wrote these mostly to start the conversation. Let's discuss that (more pragmatic) solution during the call.
