### ISSUE TITLE
Investigate Why Avalon Manifests Are Not Loading in Universal Viewer

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#351]
### Description
Avalon-generated IIIF manifests are not working properly in Universal Viewer. Investigation needs to be done to determine if this is an issue within UV or with our manifests, not implementing auth properly, or some other possibility.

### Done Looks Like
- Manifests are tested against UV 
- Evaluation is made about whether anything needs to change on our end or if UV needs to be updated to work properly with well-formed manifests

**Comment by cjcolvar** [comment]
I tested a public audio MCO manifest with UV and it failed to load.  I then checked if the manifest passed the IIIF V3 validator and it failed.  This is at least a starting point to explore.

**Comment by cjcolvar** [comment]
See notes in https://github.com/avalonmediasystem/avalon/issues/4081

**Comment by joncameron** [comment]
duplicate of https://github.com/avalonmediasystem/avalon/issues/4081
