### ISSUE TITLE
Upgrade to Hyrax 3.0/Wings

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#386]
### Descriptive summary
Lynette has an ask out for organizations to test moving their existing Hyrax apps to Hyrax 3.0 and update them to use the Valkyrie/Wings adapter.  

### Done Looks Like
- Participate in discussions and sharing on moving avalon-bundle to Hyrax 3.0
- Upgrade avalon-bundle to Hyrax 3.0 and update to use Valkyrie and the Wings adapter

**Comment by joncameron** [comment]
What are Lynette's goals? What is she planning? We're expecting that the whole week would be spent on this. We should plan to spend as long as needed. This shouldn't take us less than a week.

**Comment by cjcolvar** [comment]
Documented here: https://docs.google.com/document/d/1ytiQOQykJtGaBuWgyihF3Z2JIyhcPXg0DyxapbK3NCQ/edit#
