### ISSUE TITLE
Verify mappings for descriptive metadata to show in IIIF manifest are still good

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#92]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/2225
Originally created by @jlhardes on *Fri, 18 Aug 2017 14:53:45 GMT*

---
#1772 outlined minimal descriptive metadata to show in IIIF manifest. This needs to be reviewed and decisions made about how much description should show in IIIF manifest.

c.f. 
https://gist.github.com/jlhardes/1e3adada7410591f46b170e65dce20af

### Done Looks Like
- [x] mappings reviewed

**Comment by jlhardes** [comment]
As long as "label", "metadata", and "description" on the gist are still accurate for the IIIF AV spec, this recommended mapping looks good to me.

Overall "label" = <mods:titleInfo/title> = dcterms:title - this is a required field in Avalon and should always be populated

"metadata": "label": "Date" = <mods:originInfo/dateIssued@encoding=”edtf”> = dcterms:issued - this is a required field in Avalon and should always be populated

Any other provided fields can be included as the gist shows in "metadata". If <mods:abstract> (dcterms:abstract) is available it can be used for "description" and also included as "metadata" but it might not need to be in both places.

**Comment by jlhardes** [comment]
@jenyoung - What do you think of this mapping for the IIIF manifest?

**Comment by jenyoung** [comment]
Isn't the `summary` coming from the `abstract` field? also, there's a typo ` "metdata":[` Otherwise, yes it looks good.

**Comment by jlhardes** [comment]
Yes, the value we're using for "metadata": [{"label": "Summary"}] is the same as "description" in the gist and those are both coming from <mods:abstract> (dcterms:abstract). I don't know if we need abstract in both places but maybe we start with it in both places and review when we see an example manifest in action in the viewer?

Also, I fixed the typo. Thanks!

**Comment by jlhardes** [comment]
@jenyoung are you good with how the mappings are in the gist? I'm OK with it if you are.

**Comment by jenyoung** [comment]
looks good to me @jlhardes

**Comment by jlhardes** [comment]
"description": is now "summary": according to the spec.
