### ISSUE TITLE
Write documentation about indexed/faceted metadata

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#95]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1963
Originally created by @jlhardes on *Fri, 26 May 2017 20:22:26 GMT*

---
### Description
No information is available in Avalon documentation about what fields are indexed for searching and browsing. This should be available in general to describe the system, but also so we have a baseline to target for Avalon 7.

### Done Looks Like: 
The [Avalon Collections Guide](https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Collections+Guide) includes information about:
- What gets indexed (all Resource Description Form fields, section titles, etc)
- What's available as facets from index
- What is keyword searchable from index

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1963#issuecomment-306928623
Originally created by @jenyoung on *Wed, 07 Jun 2017 21:20:44 GMT*

---
solr info https://github.com/avalonmediasystem/avalon/blob/master/app/models/mods_behaviors.rb#L21-L91

**Comment by jenyoung** [comment]
started doc https://docs.google.com/spreadsheets/d/1wWwZlLDomfTZe3PBXVEc20POA2zhvkp1yKB9RmVPks8/edit#gid=0

**Comment by jlhardes** [comment]
Avalon Collections Guide Documentation tab in the google spreadsheet has documentation to publish there and the other tabs are start on developer documentation for Solr config-level index/sort/facet info.

**Comment by jlhardes** [comment]
There is a Browsing and Searching section in Avalon Collections Guide: https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Collections+Guide#AvalonCollectionsGuide-BrowsingandSearching

That seems like the place to put the image of this table. One thing I am noticing is that the guide says "Labels for sections are not searchable." but my testing on pawpaw suggested they are searchable. Should that be updated or are section labels not searchable?

**Comment by jlhardes** [comment]
![Avalon6Facet_Index_Search_Metadata_AvalonCollectionsGuideDocumentation.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/554375124567765f00a89464/125516c66e82c728ace21e0d46c9829b2f8d8dffa9e8bc46b062d99a2d433f4c1a01a239738ddc05ba567a050e1b1fc3301e0e18a3a7fa74faea6923ce0554b3921a1a2d926865f3ebc742ea5ffe71cf16dae8ae965e80aa627fb2d8cb5d340c001f8da95c37f3901f9b5ea44ae34d52a4173332b071367a55880c377d353379f6a59503c5976ab6bb172557cde1edfc1111a978ddc10a727118.png)

**Comment by joncameron** [comment]
This is excellent! Thanks @jenyoung and @jlhardes !
