### ISSUE TITLE
Investigate Display of Structural Metadata Within Hyrax Context

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#98]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1846
Originally created by @joncameron on *Mon, 24 Apr 2017 13:57:16 GMT*

---
### Description
This is an investigative ticket to discuss direction for the player UI and how to represent structural metadata.

### Questions

Do we want structural metadata to display within the media player, like can be done with Universal Viewer? Or should we keep structural metadata outside the player as it is in 6.x? What are pros and cons of each approach with respect to the user experience?

### Done looks like
- discussion occurs , general direction agreed upon
- documentation written
- wireframe drawn

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1846#issuecomment-299906909
Originally created by @davidschober on *Mon, 08 May 2017 15:49:24 GMT*

---
@joncameron can you rewrite this one? I"m not sure what it represents.

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1846#issuecomment-302123371
Originally created by @davidschober on *Wed, 17 May 2017 15:16:33 GMT*

---
Related to #1931

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1846#issuecomment-299262895
Originally created by @davidschober on *Thu, 04 May 2017 18:00:55 GMT*

---
@joncameron this sounds pretty critical, can you write out a description?

**Comment by davidschober** [comment]
The Stand alone player will be used, we will investigate how to display

**Comment by joncameron** [comment]
Notes from this meeting are at https://iu.app.box.com/notes/296171976807.
